// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: cache.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthCaches struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepthCaches []*DepthCache `protobuf:"bytes,1,rep,name=depthCaches,proto3" json:"depthCaches,omitempty"`
}

func (x *DepthCaches) Reset() {
	*x = DepthCaches{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthCaches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthCaches) ProtoMessage() {}

func (x *DepthCaches) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthCaches.ProtoReflect.Descriptor instead.
func (*DepthCaches) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *DepthCaches) GetDepthCaches() []*DepthCache {
	if x != nil {
		return x.DepthCaches
	}
	return nil
}

type DepthCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoardsPlayerA []uint64 `protobuf:"varint,1,rep,packed,name=boardsPlayerA,proto3" json:"boardsPlayerA,omitempty"`
	BoardsPlayerB []uint64 `protobuf:"varint,2,rep,packed,name=boardsPlayerB,proto3" json:"boardsPlayerB,omitempty"`
	BoardsTie     []uint64 `protobuf:"varint,3,rep,packed,name=boardsTie,proto3" json:"boardsTie,omitempty"`
}

func (x *DepthCache) Reset() {
	*x = DepthCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthCache) ProtoMessage() {}

func (x *DepthCache) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthCache.ProtoReflect.Descriptor instead.
func (*DepthCache) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *DepthCache) GetBoardsPlayerA() []uint64 {
	if x != nil {
		return x.BoardsPlayerA
	}
	return nil
}

func (x *DepthCache) GetBoardsPlayerB() []uint64 {
	if x != nil {
		return x.BoardsPlayerB
	}
	return nil
}

func (x *DepthCache) GetBoardsTie() []uint64 {
	if x != nil {
		return x.BoardsTie
	}
	return nil
}

var File_cache_proto protoreflect.FileDescriptor

var file_cache_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x44, 0x65, 0x70, 0x74, 0x68, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x70, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x0b, 0x64, 0x65, 0x70,
	0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0d, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x12, 0x24, 0x0a, 0x0d,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x54, 0x69, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x54, 0x69, 0x65,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x67, 0x72, 0x65, 0x6b, 0x35, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x34, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData = file_cache_proto_rawDesc
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_proto_rawDescData)
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cache_proto_goTypes = []interface{}{
	(*DepthCaches)(nil), // 0: proto.DepthCaches
	(*DepthCache)(nil),  // 1: proto.DepthCache
}
var file_cache_proto_depIdxs = []int32{
	1, // 0: proto.DepthCaches.depthCaches:type_name -> proto.DepthCache
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepthCaches); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepthCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_rawDesc = nil
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
